### ISSUE TITLE
When you issue a badge to an email address, check to see if you can auto-add it.

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadger#174] opened 2013-06-02 19:29 UTC
In the badge issuing page, (/issuers? I don't have the right kind of account and am in a hurry) when you issue a badge to a list of email addresses...if any of the email addresses already exist in the database, _automatically issue the badge to them_.

/cc @brianloveswords @erinknight

**Comment by threeqube** [comment] 2013-06-02 20:50
And have that badge display in the learner's /mybadges page.

**Comment by toolness** [comment] 2013-06-03 18:40
Can you explain the rationale behind this? Is permission from a parent only needed the first time a kid receives a badge or something?

**Comment by threeqube** [comment] 2013-06-03 18:42
This is for > 13 learners. 

For < 13 learners, parents will still gate-keep and notifications will be sent out.

**Comment by stenington** [comment] 2013-06-03 18:58
So, are we 100% sure that no guardian account will ever have badges in our CSOL instance of Open Badger? Otherwise, if they did, all of their kids' badges would get auto-awarded to the guardian instead.

**Comment by cmcavoy** [comment] 2013-06-03 20:27
> Can you explain the rationale behind this? Is permission from a parent only needed the first time a kid receives a badge or something?

It's something the city has asked for. @stenington has a good point though, if a guardian collected badges (entirely possible) or even just had an account with a single badge, they'd get their kids badges.

I'm going to call this off for the time being unless we can think of another way to handle it. The intention is to allow issuers to push badges to a users account without the user having to take action. Because all issuers are 'trusted' we want to push automatically similar to backpack-connect.

**Comment by cmcavoy** [comment] 2013-06-04 01:30
After some discussion with @erinknight we're going to restrict usage of the site to users born after 1980 and message "youth signup" somehow to imply that this is for you kids, not for you. Which means we can go ahead with the original implementation plan at the top of the ticket, and assume that if the email exists in the system already we auto-award to it.

We'll have an FAQ and a monitored support@csol email address that people can write if there's a conflict, we can resolve it case by case.

**Comment by toolness** [comment] 2013-06-04 21:19
I think this should be something that CSOL-site does when it's notified by openbadger that a reserved claim code for a user has been created (see #128). This helps keep all the COPPA logic out of openbadger and delegates it to CSOL-site, which knows more about the age levels of people, and thus knows for sure whether the badge can be auto awarded. One benefit of this solution, for instance, is that it will be able to auto-award even the _first_ badge a > 13 learner earns, before any badges for them exist in openbadger's database.

**Comment by ghost** [comment] 2013-06-04 21:21
Yeah, agree with @toolness.  I've got something supporting this in my WIP pull request here: https://github.com/mozilla/CSOL-site/pull/391

**Comment by cmcavoy** [comment] 2013-06-05 00:46
Hey Guys, I'm not suggesting we check CSOL-site. I'm suggesting we check OpenBadger. We have a list in OpenBadger of all the issued badges...check against the list of all the emails that those badges have been awarded to.

If a user is < 13 on CSOL they have a fake email address in OpenBadger. So, unless the issuer knows the fake email address, they can't directly award a badge to < 13 year old. They'll have to use the guardian email, which triggers an actual email notification and guardian approval step.

So...unless significant work has been done, this seems way easier to do by checking openbadger locally.

**Comment by toolness** [comment] 2013-06-05 02:47
Significant work has already been done, because we already need openbadger to delegate lots of coppa-specific logic to CSOL-site. So yes, it will be easier to implement the auto-add from CSOL-site's end.

**Comment by toolness** [comment] 2013-06-07 11:56
I believe this has been done by Lord Christensen's CSOL-site PR, specifically the code [right here](https://github.com/mozilla/CSOL-site/pull/391/files#L1R22). Closing this ticket!

**Comment by cmcavoy** [comment] 2013-06-13 15:18
Just tried this in production. I issued a badge to chris.mcavoy@gmail.com, who has already earned badges. The claim code was created and is reserved for chris.mcavoy@gmail.com, but chris.mcavoy@gmail.com never got a notification, and the badge isn't in his (my) backpack.

**Comment by toolness** [comment] 2013-06-13 15:23
If this is happening, it's not a bug in openbadger, it's a bug in mozilla/CSOL-site#391, because CSOL-site is responsible for auto-awarding badges if it deems them necessary. Which is odd, because [this code](https://github.com/mozilla/CSOL-site/pull/391/files#L1R21) should be claiming the badge, so at the very least it should appear in your backpack. Any ideas, @christensenep ?

**Comment by toolness** [comment] 2013-06-13 15:43
So it looks like the code currently doesn't send any email because Erik was never given any content for such an email. However, the code _is_ auto-awarding the badge, and that works locally, but it's odd that it's not working for your email. Is chris.mcavoy@gmail.com marked as an underage learner?

**Comment by ghost** [comment] 2013-06-13 15:47
Aye, I was under the impression that no email was sent in the case of an auto-awarded badge (which occurs when a >13 learner is issued a badge and already has an account).  It's certainly very easy to make it send an email, though as @toolness mentions, I don't think I have any copy for an email in that case.

Still looking into the actual bug of not auto-awarded the badge, though.

**Comment by cmcavoy** [comment] 2013-06-13 15:50
No I'm registered as over 13.

**Comment by cmcavoy** [comment] 2013-06-13 15:51
No email is necessary...as long as the badge is issued.

**Comment by ghost** [comment] 2013-06-13 17:19
So I was looking through mandrill's logs, and I noticed that earlier today there was an email sent to chrismcavoy@gmail.com (as opposed to chris.mcavoy@gmail.com) using the "unknown user" template.  This was around the time that you reported this issue, so I wanted to make sure that they aren't related.  Was this a separate issuance, or is it possible there was just a missing period in the email address?

**Comment by cmcavoy** [comment] 2013-06-13 17:57
You can drop periods into gmail addresses, its a good way to
test...infinite emails! I got the periodless email, but not the period
email. I registered with the period email.

**Comment by ghost** [comment] 2013-06-13 18:11
Ah, ok, just checking.  That would have been too easy, clearly. :)

**Comment by ghost** [comment] 2013-06-13 20:37
Alright, thanks to @toolness, the mystery is solved.  It was not working this morning because CSOL-site was trying to claim the badge via <b>http</b>://badge.chicagosummeroflearning.org/v2/claim.  By the time you tried again, the environment had changed such that it was now (correctly) pointing to <b>https</b>://badge.chicagosummeroflearning.org/v2/claim.  So it should be working now!

**Closed as completed** 2013-12-03 21:12 UTC
